import { QuestionDef } from '../types'

/**
 * This is the "question bank" described in the architecture doc — a static,
 * pre-written, pre-tagged table (here: an array, standing in for the
 * PostgreSQL Question table). The app filters and orders this by role;
 * nothing here is generated by an LLM.
 */
export const QUESTION_BANK: QuestionDef[] = [
  // ---------- Business Owner ----------
  {
    id: 'Q-BIZ-001',
    domain: 'Business',
    roles: ['Business Owner'],
    question: 'What is the primary business problem this project solves?',
    options: ['Reduce cost', 'Increase revenue', 'Improve customer experience', 'Reduce risk'],
    mandatory: true
  },
  {
    id: 'Q-BIZ-002',
    domain: 'Business',
    roles: ['Business Owner'],
    question: "What's the primary success metric for this project?",
    options: ['Cost reduction', 'Revenue growth', 'Customer satisfaction score', 'Time saved'],
    mandatory: true
  },
  {
    id: 'Q-BIZ-003',
    domain: 'Budget',
    roles: ['Business Owner'],
    question: 'What is the approximate budget range for this project?',
    options: ['Under $25k', '$25k - $100k', '$100k - $500k', '$500k+'],
    mandatory: true
  },
  {
    id: 'Q-BIZ-004',
    domain: 'Timeline',
    roles: ['Business Owner'],
    question: 'What is your target timeline for launch?',
    options: ['Under 3 months', '3-6 months', '6-12 months', 'No fixed deadline'],
    mandatory: true
  },

  {
    id: 'Q-BIZ-005',
    domain: 'Stakeholders',
    roles: ['Business Owner'],
    question: 'Who are the key stakeholders that need to sign off on this?',
    options: ['Just me', 'A small leadership team', 'Multiple departments', 'Board-level approval needed'],
    mandatory: true
  },
  {
    id: 'Q-BIZ-006',
    domain: 'Business',
    roles: ['Business Owner'],
    question: 'Is there an existing solution this replaces?',
    options: ['Yes, an in-house tool', 'Yes, a third-party product', 'No, this is net new', 'Partially, some manual process'],
    mandatory: true
  },
  {
    id: 'Q-BIZ-007',
    domain: 'Risks',
    roles: ['Business Owner'],
    question: 'What would make this project fail from your perspective?',
    options: ['Missed deadline', 'Over budget', 'Low adoption', 'Not solving the real problem'],
    mandatory: true
  },

  // ---------- Product Manager ----------
  {
    id: 'Q-PM-001',
    domain: 'Users',
    roles: ['Product Manager', 'Business Owner'],
    question: 'Roughly how many people will use this system?',
    options: ['Under 100', '100 - 1,000', '1,000 - 50,000', '50,000+'],
    mandatory: true
  },
  {
    id: 'Q-PM-002',
    domain: 'Functional Requirements',
    roles: ['Product Manager'],
    question: 'What is the single most important feature for launch?',
    options: ['Automated responses', 'Human handoff', 'Multi-language support', 'Analytics dashboard'],
    mandatory: true
  },
  {
    id: 'Q-PM-003',
    domain: 'Functional Requirements',
    roles: ['Product Manager'],
    question: 'Should this support multiple channels (chat, email, phone)?',
    options: ['Chat only', 'Chat + email', 'All channels', 'Not decided yet'],
    mandatory: true
  },
  {
    id: 'Q-PM-004',
    domain: 'Success Metrics',
    roles: ['Product Manager'],
    question: 'How will you measure whether this product is working?',
    options: ['Resolution time', 'Customer satisfaction', 'Ticket deflection rate', 'Adoption rate'],
    mandatory: true
  },
  {
    id: 'Q-PM-005',
    domain: 'Functional Requirements',
    roles: ['Product Manager'],
    question: "What's out of scope for the first version?",
    options: ['Advanced analytics', 'Multi-language', 'Voice support', 'Not decided yet'],
    mandatory: true
  },
  {
    id: 'Q-PM-006',
    domain: 'Users',
    roles: ['Product Manager'],
    question: 'Who is the primary end user of this product?',
    options: ['Internal employees', 'External customers', 'Both', 'A specific customer segment'],
    mandatory: true
  },
  {
    id: 'Q-PM-007',
    domain: 'Functional Requirements',
    roles: ['Product Manager'],
    question: 'Does this need an admin or management interface?',
    options: ['Yes, full admin panel', 'Yes, basic settings only', 'No', 'Not decided yet'],
    mandatory: true
  },

  // ---------- Technical Lead ----------
  {
    id: 'Q-TECH-001',
    domain: 'Integrations',
    roles: ['Technical Lead'],
    question: 'What should this system integrate with?',
    options: ['CRM', 'Helpdesk software', 'Order/database system', 'None yet'],
    mandatory: true
  },
  {
    id: 'Q-INFRA-002',
    domain: 'Deployment',
    roles: ['Technical Lead', 'IT/Infrastructure'],
    question: 'Where should this be deployed?',
    options: ['AWS', 'Azure', 'GCP', 'On-premise'],
    mandatory: true
  },
  {
    id: 'Q-TECH-003',
    domain: 'Technology',
    roles: ['Technical Lead'],
    question: 'Are there existing systems this must be built alongside?',
    options: ['Legacy monolith', 'Existing microservices', 'Greenfield, nothing existing', 'Not sure yet'],
    mandatory: true
  },
  {
    id: 'Q-TECH-004',
    domain: 'Non-Functional Requirements',
    roles: ['Technical Lead'],
    question: 'What are the expected concurrent users at peak?',
    options: ['Under 50', '50 - 500', '500 - 5,000', '5,000+'],
    mandatory: true
  },
  {
    id: 'Q-TECH-005',
    domain: 'Architecture',
    roles: ['Technical Lead'],
    question: 'Do you have a preferred backend language or framework?',
    options: ['Python', 'Node.js / TypeScript', 'Java / JVM', 'No preference'],
    mandatory: true
  },
  {
    id: 'Q-TECH-006',
    domain: 'Technology',
    roles: ['Technical Lead'],
    question: 'Should this be a single application or split into services?',
    options: ['Single application', 'Microservices from day one', 'Not sure, want a recommendation', 'Depends on scale'],
    mandatory: true
  },
  {
    id: 'Q-TECH-007',
    domain: 'Non-Functional Requirements',
    roles: ['Technical Lead'],
    question: 'Is real-time or near-real-time response required?',
    options: ['Yes, under 1 second', 'A few seconds is fine', 'Minutes are acceptable', 'Not time sensitive'],
    mandatory: true
  },
  {
    id: 'Q-TECH-008',
    domain: 'Data',
    roles: ['Technical Lead'],
    question: 'Where will the primary data for this system live?',
    options: ['New database we design', 'Existing company database', 'Third-party data source', 'Not decided yet'],
    mandatory: true
  },

  // ---------- Data / AI Lead ----------
  {
    id: 'Q-DATA-001',
    domain: 'Data',
    roles: ['Data/AI Lead'],
    question: 'What type of data will the system process?',
    options: ['Public information', 'Internal business information', 'Personally identifiable information', 'Financial / highly sensitive information'],
    mandatory: true
  },
  {
    id: 'Q-DATA-002',
    domain: 'AI/ML',
    roles: ['Data/AI Lead'],
    question: 'Do you have existing training data or examples for this AI system?',
    options: ['Yes, well documented', 'Yes, but messy', 'No, starting from scratch', 'Not applicable'],
    mandatory: true
  },
  {
    id: 'Q-DATA-003',
    domain: 'AI/ML',
    roles: ['Data/AI Lead'],
    question: 'How should low-confidence AI responses be handled?',
    options: ['Escalate to a human', 'Ask a clarifying question', 'Answer with a disclaimer', 'Not decided yet'],
    mandatory: true
  },
  {
    id: 'Q-DATA-004',
    domain: 'Data',
    roles: ['Data/AI Lead'],
    question: 'Where does this data currently live?',
    options: ['Existing CRM', 'Spreadsheets/exports', 'A data warehouse', 'It does not exist yet'],
    mandatory: true
  },
  {
    id: 'Q-DATA-005',
    domain: 'AI/ML',
    roles: ['Data/AI Lead'],
    question: 'Do you have a preference between a hosted LLM provider and a self-hosted model?',
    options: ['Hosted (OpenAI/Anthropic/etc.)', 'Self-hosted open source', 'No preference', 'Need a recommendation'],
    mandatory: true
  },
  {
    id: 'Q-DATA-006',
    domain: 'AI/ML',
    roles: ['Data/AI Lead'],
    question: 'How will you evaluate whether the AI is performing well?',
    options: ['Manual spot-checks', 'Automated eval suite', 'User feedback / ratings', 'Not decided yet'],
    mandatory: true
  },
  {
    id: 'Q-DATA-007',
    domain: 'Data',
    roles: ['Data/AI Lead'],
    question: 'How often does the underlying data change?',
    options: ['Real-time / constantly', 'Daily', 'Weekly or monthly', 'Rarely changes'],
    mandatory: true
  },
  {
    id: 'Q-DATA-008',
    domain: 'AI/ML',
    roles: ['Data/AI Lead'],
    question: 'Should the AI have access to take actions, or only answer questions?',
    options: ['Answer only', 'Can take limited actions with approval', 'Can act autonomously', 'Not decided yet'],
    mandatory: true
  },

  // ---------- Security / Compliance ----------
  {
    id: 'Q-SEC-014',
    domain: 'Security',
    roles: ['Security/Compliance', 'Technical Lead'],
    question: 'Do you already have an authentication system in place?',
    options: ['Yes - Azure AD', 'Yes - Okta', 'Yes - custom', 'Not yet'],
    mandatory: true
  },
  {
    id: 'Q-SEC-002',
    domain: 'Security',
    roles: ['Security/Compliance'],
    question: 'Which user groups should be allowed to access the system?',
    options: ['All employees', 'Specific department only', 'Customers directly', 'Not decided yet'],
    mandatory: true,
    dependsOn: 'Q-SEC-014'
  },
  {
    id: 'Q-COMP-001',
    domain: 'Compliance',
    roles: ['Security/Compliance'],
    question: 'Are there specific compliance requirements this must meet?',
    options: ['GDPR', 'HIPAA', 'SOC 2', 'None known'],
    mandatory: true
  },
  {
    id: 'Q-SEC-003',
    domain: 'Security',
    roles: ['Security/Compliance'],
    question: 'Is there a data residency requirement (e.g. data must stay in-region)?',
    options: ['Yes, must stay in one region', 'No restriction', 'Not sure', 'Depends on customer'],
    mandatory: true
  },
  {
    id: 'Q-SEC-004',
    domain: 'Security',
    roles: ['Security/Compliance'],
    question: 'Should all data be encrypted at rest and in transit?',
    options: ['Yes, both required', 'In transit only', 'Not sure', 'To be determined by IT'],
    mandatory: true
  },
  {
    id: 'Q-COMP-002',
    domain: 'Compliance',
    roles: ['Security/Compliance'],
    question: 'Is there an audit logging requirement for this system?',
    options: ['Yes, full audit trail required', 'Basic logging is fine', 'Not required', 'Not sure'],
    mandatory: true
  },
  {
    id: 'Q-SEC-005',
    domain: 'Security',
    roles: ['Security/Compliance'],
    question: 'Will this system need to support single sign-on (SSO)?',
    options: ['Yes, required', 'Nice to have', 'Not needed', 'Not sure'],
    mandatory: true
  },
  {
    id: 'Q-COMP-003',
    domain: 'Risks',
    roles: ['Security/Compliance'],
    question: 'Has a security or privacy review been done for similar projects before?',
    options: ['Yes, we have a process', 'No, this would be the first', 'Not sure', 'Depends on the vendor'],
    mandatory: true
  },

  // ---------- IT / Infrastructure ----------
  {
    id: 'Q-IT-001',
    domain: 'Infrastructure',
    roles: ['IT/Infrastructure'],
    question: 'What is your current hosting setup?',
    options: ['Cloud-native already', 'On-premise data center', 'Hybrid', 'None yet'],
    mandatory: true
  },
  {
    id: 'Q-IT-002',
    domain: 'Operations',
    roles: ['IT/Infrastructure'],
    question: 'What is your expectation for uptime / availability?',
    options: ['Best effort', '99% uptime', '99.9% uptime', '99.99%+ uptime'],
    mandatory: true
  },
  {
    id: 'Q-IT-003',
    domain: 'Operations',
    roles: ['IT/Infrastructure'],
    question: 'Do you have an existing disaster recovery plan?',
    options: ['Yes, documented', 'Informal / ad-hoc', 'No plan yet', 'Not applicable'],
    mandatory: true
  },
  {
    id: 'Q-IT-004',
    domain: 'Monitoring',
    roles: ['IT/Infrastructure'],
    question: 'What monitoring or observability tools do you currently use?',
    options: ['Datadog', 'Grafana/Prometheus', 'CloudWatch', 'None yet'],
    mandatory: true
  },
  {
    id: 'Q-IT-005',
    domain: 'Operations',
    roles: ['IT/Infrastructure'],
    question: 'Do you need a staging/test environment separate from production?',
    options: ['Yes, staging and prod', 'Yes, dev/staging/prod', 'Production only for now', 'Not sure'],
    mandatory: true
  },
  {
    id: 'Q-IT-006',
    domain: 'Infrastructure',
    roles: ['IT/Infrastructure'],
    question: 'How should this system scale under load?',
    options: ['Auto-scale automatically', 'Manual scaling is fine', 'Fixed capacity is fine', 'Not sure yet'],
    mandatory: true
  },
  {
    id: 'Q-IT-007',
    domain: 'Operations',
    roles: ['IT/Infrastructure'],
    question: 'Who will be responsible for ongoing maintenance after launch?',
    options: ['Internal IT team', 'The consulting firm', 'A mix of both', 'Not decided yet'],
    mandatory: true
  },
  {
    id: 'Q-IT-008',
    domain: 'Infrastructure',
    roles: ['IT/Infrastructure'],
    question: 'Is there an existing CI/CD pipeline this should plug into?',
    options: ['Yes, GitHub Actions', 'Yes, another tool', 'No, needs to be set up', 'Not sure'],
    mandatory: true
  }
]

/**
 * Ideation / "make it better" questions — separate from gap-filling.
 * A gap question exists because something is *missing* and blocks
 * scoping (budget, compliance, hosting). An ideation question exists
 * even when nothing is missing — it's the kind of thing a sharp
 * consultant (or Claude) volunteers unprompted: what should the
 * homepage lead with, what would make users choose this over the
 * incumbent, what's the one feature that would delight someone on day
 * one. Not industry-gated — every role/project benefits from being
 * asked to think about what would make the product *better*, not just
 * complete.
 */
const GENERIC_IDEATION_QUESTIONS: QuestionDef[] = [
  {
    id: 'Q-IDEA-001',
    domain: 'Product Ideation',
    roles: ['Product Manager', 'Business Owner'],
    question: 'What should someone see first when they open the app or land on the homepage?',
    options: [
      'Personalized content picked for them',
      'A simple, clear call-to-action to get started',
      'Trending / most popular content',
      'A guided setup or onboarding flow'
    ],
    mandatory: false,
    category: 'ideation'
  },
  {
    id: 'Q-IDEA-002',
    domain: 'Product Ideation',
    roles: ['Product Manager', 'Business Owner'],
    question: 'What would make someone choose this over the closest existing alternative?',
    options: [
      'A better/simpler experience',
      'A feature competitors lack',
      'Lower price or a free tier',
      'Not sure yet — open to suggestions'
    ],
    mandatory: false,
    category: 'ideation'
  },
  {
    id: 'Q-IDEA-003',
    domain: 'Product Ideation',
    roles: ['Product Manager', 'Business Owner'],
    question: 'If you could add one "delight" feature beyond the core requirements, what would move the needle most?',
    options: [
      'Something personalized/AI-driven',
      'A social or sharing feature',
      'A gamification or rewards element',
      'Not sure — open to suggestions'
    ],
    mandatory: false,
    category: 'ideation'
  },
  {
    id: 'Q-IDEA-004',
    domain: 'Product Ideation',
    roles: ['Product Manager'],
    question: 'How should a brand-new user be guided through their very first session?',
    options: [
      'Interactive step-by-step onboarding',
      'Let them explore freely, no tutorial',
      'A short welcome video or tour',
      'Ask a few preference questions up front'
    ],
    mandatory: false,
    category: 'ideation'
  }
]

export function questionsForRole(role: string, projectContext?: string): QuestionDef[] {
  const base = QUESTION_BANK.filter((q) => q.roles.includes(role as any))
  const ideation = GENERIC_IDEATION_QUESTIONS.filter((q) => q.roles.includes(role as any))
  const withIdeation = [...base, ...ideation]
  if (!projectContext) return withIdeation

  const industryQuestions = questionsForIndustry(projectContext, role)
  // de-dupe by id in case of overlap
  const ids = new Set(withIdeation.map((q) => q.id))
  return [...withIdeation, ...industryQuestions.filter((q) => !ids.has(q.id))]
}

/**
 * Industry-specific question bank — the piece that was missing. Without
 * this, every project of any type got the exact same generic 9 questions
 * per role, regardless of whether it was a music app or a hospital
 * scheduling tool. Detected via keyword matching against the project name
 * (and document text, when a file was uploaded) — a rule-based stand-in
 * for a real project-type classifier, same as the rest of the "ML" in
 * this app right now.
 */
export const INDUSTRY_KEYWORDS: Record<string, string[]> = {
  music: ['music', 'song', 'stream', 'playlist', 'audio', 'artist', 'album', 'podcast'],
  ecommerce: ['shop', 'store', 'ecommerce', 'e-commerce', 'retail', 'cart', 'checkout', 'product catalog'],
  healthcare: ['patient', 'health', 'clinic', 'hospital', 'medical', 'diagnosis', 'appointment', 'ehr'],
  fintech: ['bank', 'payment', 'fintech', 'loan', 'invoice', 'wallet', 'transaction', 'ledger'],
  support: ['support', 'helpdesk', 'ticket', 'customer service', 'chatbot']
}

export function detectIndustries(text: string): string[] {
  const lowered = text.toLowerCase()
  return Object.entries(INDUSTRY_KEYWORDS)
    .filter(([, keywords]) => keywords.some((k) => lowered.includes(k)))
    .map(([industry]) => industry)
}

const INDUSTRY_QUESTIONS: QuestionDef[] = [
  // ---------- Music / streaming ----------
  {
    id: 'Q-MUSIC-001',
    domain: 'Licensing',
    roles: ['Business Owner', 'Product Manager'],
    question: 'How will music content be sourced and licensed?',
    options: ['Direct label licensing agreements', 'Independent artists upload directly', 'Royalty-free / public domain only', 'A combination of sources'],
    mandatory: true
  },
  {
    id: 'Q-MUSIC-002',
    domain: 'Licensing',
    roles: ['Business Owner'],
    question: 'How will royalties be calculated and paid to rights holders?',
    options: ['Per-stream royalty model', 'Fixed licensing fee', 'Handled by the label, not us', 'Not decided yet'],
    mandatory: true
  },
  {
    id: 'Q-MUSIC-003',
    domain: 'Functional Requirements',
    roles: ['Product Manager'],
    question: 'Should users be able to download tracks for offline listening?',
    options: ['Yes, all users', 'Yes, premium tier only', 'No', 'Not decided yet'],
    mandatory: true
  },
  {
    id: 'Q-MUSIC-004',
    domain: 'Technology',
    roles: ['Technical Lead'],
    question: 'What audio streaming quality tiers need to be supported?',
    options: ['Standard quality only', 'Standard + HD', 'Lossless / hi-fi included', 'Not decided yet'],
    mandatory: true
  },
  {
    id: 'Q-MUSIC-005',
    domain: 'Data',
    roles: ['Data/AI Lead'],
    question: 'Will you need music recommendation or personalization features?',
    options: ['Yes, personalized recommendations', 'Yes, simple genre-based only', 'No, browse/search only', 'Not decided yet'],
    mandatory: true
  },
  {
    id: 'Q-MUSIC-006',
    domain: 'Functional Requirements',
    roles: ['Product Manager'],
    question: 'Should the app support collaborative or shared playlists?',
    options: ['Yes, collaborative editing', 'Yes, but view-only sharing', 'No, personal playlists only', 'Not decided yet'],
    mandatory: true
  },
  {
    id: 'Q-MUSIC-007',
    domain: 'AI/ML',
    roles: ['Data/AI Lead'],
    question: "How important is a personalized \"For You\" discovery feed?",
    options: ['Core to the product', 'Nice to have', 'Not needed at launch', 'Not decided yet'],
    mandatory: true
  },
  {
    id: 'Q-MUSIC-008',
    domain: 'Functional Requirements',
    roles: ['Product Manager'],
    question: 'Should users be able to follow artists and see updates from them?',
    options: ['Yes, full artist profiles', 'Yes, basic following only', 'No', 'Not decided yet'],
    mandatory: true
  },
  {
    id: 'Q-MUSIC-009',
    domain: 'Technology',
    roles: ['Technical Lead'],
    question: 'What audio codec and transcoding pipeline does the backend need to support?',
    options: ['A single standard codec (e.g. AAC)', 'Multiple codecs for device compatibility', 'Lossless/FLAC support required', 'Not decided yet'],
    mandatory: true
  },
  {
    id: 'Q-MUSIC-010',
    domain: 'Business',
    roles: ['Business Owner'],
    question: 'Will the app support an ad-supported free tier alongside premium?',
    options: ['Yes, freemium with ads', 'No, subscription only', 'Depends on market', 'Not decided yet'],
    mandatory: true
  },
  {
    id: 'Q-MUSIC-011',
    domain: 'Licensing',
    roles: ['Technical Lead'],
    question: 'Does the catalog need DRM or content protection for offline downloads?',
    options: ['Yes, required by labels', 'No DRM needed', 'Depends on the licensing deal', 'Not sure yet'],
    mandatory: true
  },
  {
    id: 'Q-MUSIC-012',
    domain: 'Functional Requirements',
    roles: ['Product Manager'],
    question: 'Should the app support podcasts in addition to music?',
    options: ['Yes, from launch', 'Maybe in a future version', 'No, music only', 'Not decided yet'],
    mandatory: true
  },
  {
    id: 'Q-MUSIC-013',
    domain: 'AI/ML',
    roles: ['Data/AI Lead'],
    question: 'How should explicit content be handled?',
    options: ['Filtered by default, opt-in to show', 'Always shown with a label', 'Blocked entirely', 'Not decided yet'],
    mandatory: true
  },
  {
    id: 'Q-MUSIC-014',
    domain: 'Business',
    roles: ['Business Owner'],
    question: 'Are family or multi-user household plans part of the plan?',
    options: ['Yes, planned at launch', 'Yes, but later', 'No', 'Not decided yet'],
    mandatory: true
  },
  {
    id: 'Q-MUSIC-015',
    domain: 'Technology',
    roles: ['Technical Lead'],
    question: 'Should playback hand off seamlessly across devices (phone to speaker, etc.)?',
    options: ['Yes, seamless handoff required', 'Nice to have', 'Not needed', 'Not decided yet'],
    mandatory: true
  },

  // ---------- Music / streaming — ideation ----------
  {
    id: 'Q-MUSIC-IDEA-001',
    domain: 'Product Ideation',
    roles: ['Product Manager', 'Business Owner'],
    question: "What should the app's home screen lead with?",
    options: [
      'A personalized "For You" mix',
      'New releases from followed artists',
      'Editorially curated playlists',
      'Trending / most-played right now'
    ],
    mandatory: false,
    category: 'ideation'
  },
  {
    id: 'Q-MUSIC-IDEA-002',
    domain: 'Product Ideation',
    roles: ['Product Manager', 'Business Owner'],
    question: 'What genres or moods should be prioritized at launch to define the catalog identity?',
    options: [
      'Broad, mainstream coverage across all genres',
      'A curated niche (e.g. indie, electronic, hip-hop)',
      'Mood/activity-based (workout, focus, chill)',
      'Not decided — open to a recommendation'
    ],
    mandatory: false,
    category: 'ideation'
  },
  {
    id: 'Q-MUSIC-IDEA-003',
    domain: 'Product Ideation',
    roles: ['Product Manager', 'Business Owner'],
    question: 'What would make a listener pick this over Spotify or Apple Music?',
    options: [
      'A tighter, more curated catalog',
      'Better support for a specific niche/community',
      'A unique social or discovery feature',
      'Not sure yet — open to suggestions'
    ],
    mandatory: false,
    category: 'ideation'
  },

  // ---------- E-commerce ----------
  {
    id: 'Q-ECOM-001',
    domain: 'Functional Requirements',
    roles: ['Product Manager'],
    question: 'What payment methods need to be supported at checkout?',
    options: ['Credit/debit cards only', 'Cards + digital wallets (Apple/Google Pay)', 'Cards + Buy Now Pay Later', 'Not decided yet'],
    mandatory: true
  },
  {
    id: 'Q-ECOM-002',
    domain: 'Integrations',
    roles: ['Technical Lead'],
    question: 'What inventory or fulfillment system should this connect to?',
    options: ['Shopify', 'A custom warehouse system', 'A third-party 3PL', 'None yet'],
    mandatory: true
  },
  {
    id: 'Q-ECOM-003',
    domain: 'Compliance',
    roles: ['Security/Compliance'],
    question: 'Do you need PCI-DSS compliance for handling card data directly?',
    options: ['Yes, we handle cards directly', 'No, using a payment processor', 'Not sure', 'Not decided yet'],
    mandatory: true
  },
  {
    id: 'Q-ECOM-004',
    domain: 'Functional Requirements',
    roles: ['Product Manager'],
    question: 'Should the app support wishlists or save-for-later?',
    options: ['Yes, wishlists', 'Yes, save for later', 'Both', 'Not decided yet'],
    mandatory: true
  },
  {
    id: 'Q-ECOM-005',
    domain: 'AI/ML',
    roles: ['Data/AI Lead'],
    question: 'Should product recommendations be personalized?',
    options: ['Yes, personalized', 'Generic bestsellers only', 'No recommendations', 'Not decided yet'],
    mandatory: true
  },

  // ---------- E-commerce — ideation ----------
  {
    id: 'Q-ECOM-IDEA-001',
    domain: 'Product Ideation',
    roles: ['Product Manager', 'Business Owner'],
    question: 'What should shoppers see first on the homepage?',
    options: [
      'Bestsellers / trending products',
      'Personalized picks based on browsing history',
      'Current promotions or deals',
      'A curated "new arrivals" showcase'
    ],
    mandatory: false,
    category: 'ideation'
  },
  {
    id: 'Q-ECOM-IDEA-002',
    domain: 'Product Ideation',
    roles: ['Product Manager', 'Business Owner'],
    question: 'What would make a shopper trust this store over a marketplace like Amazon?',
    options: [
      'Stronger brand story / curation',
      'Better customer service or return policy',
      'Reviews and social proof front and center',
      'Not sure yet — open to suggestions'
    ],
    mandatory: false,
    category: 'ideation'
  },

  // ---------- Healthcare ----------
  {
    id: 'Q-HEALTH-001',
    domain: 'Compliance',
    roles: ['Security/Compliance'],
    question: 'Will this system store or transmit protected health information (PHI)?',
    options: ['Yes, PHI is central to this system', 'Yes, but minimal PHI', 'No PHI involved', 'Not sure yet'],
    mandatory: true
  },
  {
    id: 'Q-HEALTH-002',
    domain: 'Integrations',
    roles: ['Technical Lead'],
    question: 'Does this need to integrate with an existing EHR system?',
    options: ['Yes - Epic', 'Yes - Cerner', 'Yes - another EHR', 'No EHR integration needed'],
    mandatory: true
  },
  {
    id: 'Q-HEALTH-003',
    domain: 'Functional Requirements',
    roles: ['Product Manager'],
    question: 'Should patients be able to message their care team directly?',
    options: ['Yes, secure messaging', 'No, phone only', 'Depends on the clinic', 'Not decided yet'],
    mandatory: true
  },
  {
    id: 'Q-HEALTH-004',
    domain: 'Functional Requirements',
    roles: ['Technical Lead'],
    question: 'Should the app support telehealth video visits?',
    options: ['Yes, required', 'Maybe a future phase', 'No, in-person only', 'Not decided yet'],
    mandatory: true
  },

  // ---------- Healthcare — ideation ----------
  {
    id: 'Q-HEALTH-IDEA-001',
    domain: 'Product Ideation',
    roles: ['Product Manager', 'Business Owner'],
    question: 'What should a patient see first when they open the app?',
    options: [
      'Their next upcoming appointment',
      'A quick way to message their care team',
      'Recent test results or health summary',
      'A prompt to book something'
    ],
    mandatory: false,
    category: 'ideation'
  },

  // ---------- Fintech ----------
  {
    id: 'Q-FIN-001',
    domain: 'Compliance',
    roles: ['Security/Compliance'],
    question: 'What financial compliance requirements apply to this project?',
    options: ['PCI-DSS', 'SOX', 'AML/KYC requirements', 'Not sure yet'],
    mandatory: true
  },
  {
    id: 'Q-FIN-002',
    domain: 'Security',
    roles: ['Security/Compliance', 'Technical Lead'],
    question: 'Does this system need to reconcile transactions against a ledger?',
    options: ['Yes, real-time reconciliation', 'Yes, batch/daily reconciliation', 'No ledger involved', 'Not decided yet'],
    mandatory: true
  },
  {
    id: 'Q-FIN-003',
    domain: 'Functional Requirements',
    roles: ['Product Manager'],
    question: 'Should employees be able to submit receipts via photo upload?',
    options: ['Yes, required', 'Yes, optional', 'No, manual entry only', 'Not decided yet'],
    mandatory: true
  },
  {
    id: 'Q-FIN-004',
    domain: 'Integrations',
    roles: ['Technical Lead'],
    question: 'Should this integrate with an accounting system like QuickBooks?',
    options: ['Yes - QuickBooks', 'Yes - another system', 'No, standalone', 'Not decided yet'],
    mandatory: true
  },

  // ---------- Fintech — ideation ----------
  {
    id: 'Q-FIN-IDEA-001',
    domain: 'Product Ideation',
    roles: ['Product Manager', 'Business Owner'],
    question: 'What would make a user trust this app with their money?',
    options: [
      'Clear, transparent fees shown up front',
      'Visible security/compliance badges',
      'Human support easily reachable',
      'Not sure yet — open to suggestions'
    ],
    mandatory: false,
    category: 'ideation'
  }
]

const INDUSTRY_ID_PREFIX: Record<string, string> = {
  music: 'Q-MUSIC',
  ecommerce: 'Q-ECOM',
  healthcare: 'Q-HEALTH',
  fintech: 'Q-FIN',
  support: 'Q-SUPPORT'
}

export function questionsForIndustry(projectContext: string, role: string): QuestionDef[] {
  const industries = detectIndustries(projectContext)
  const prefixes = industries.map((ind) => INDUSTRY_ID_PREFIX[ind]).filter(Boolean)
  return INDUSTRY_QUESTIONS.filter(
    (q) => q.roles.includes(role as any) && prefixes.some((prefix) => q.id.startsWith(prefix))
  )
}

/**
 * Domain criticality weights — the "Criticality" term in the next-best-
 * question scoring formula (Part 13 of the system design doc):
 *   Score(Q) = InformationGain × Criticality × RoleRelevance − DependencyPenalty
 * Higher = more important to resolve early. These are hand-set for the
 * MVP; a real XGBoost gap model would eventually learn these instead of
 * having them hard-coded, but the formula shape stays identical either way.
 */
export const DOMAIN_CRITICALITY: Record<string, number> = {
  Security: 5,
  Compliance: 5,
  Data: 4,
  'AI/ML': 4,
  Deployment: 4,
  Business: 3,
  Users: 3,
  'Functional Requirements': 3,
  'Non-Functional Requirements': 3,
  Integrations: 3,
  Technology: 3,
  Architecture: 3,
  Infrastructure: 3,
  Operations: 2,
  Monitoring: 2,
  Budget: 2,
  Timeline: 2,
  Stakeholders: 2,
  'Success Metrics': 2,
  Risks: 3,
  // Ideation questions are intentionally lower-weighted than any gap
  // domain — gaps that block scoping get resolved first, ideation
  // questions fill in once the fundamentals are covered, same as a
  // human consultant would sequence a conversation.
  'Product Ideation': 1
}

/**
 * Real next-best-question selection — replaces "first eligible in list
 * order" with the actual scoring formula. Every mandatory question here
 * has equal information gain (all are unresolved, unweighted otherwise),
 * so with role relevance fixed at 1 (already filtered to this role), this
 * reduces to: highest domain criticality among dependency-eligible
 * questions wins. That's a real, honest ranking — not a random order —
 * and it's the same formula shape a future ML ranking model would slot
 * into without changing anything downstream.
 */
export function selectNextQuestion(
  eligible: QuestionDef[]
): QuestionDef | undefined {
  if (eligible.length === 0) return undefined
  return [...eligible].sort((a, b) => {
    const scoreA = (DOMAIN_CRITICALITY[a.domain] ?? 2) * (a.mandatory ? 1 : 0.5)
    const scoreB = (DOMAIN_CRITICALITY[b.domain] ?? 2) * (b.mandatory ? 1 : 0.5)
    return scoreB - scoreA
  })[0]
}
